import type { SEOProps } from '../components/SEO'

const BASE_KEYWORDS = 'قبيلة النعيم أهل الصفرا ٥١٥, النعيم ٥١٥, السادة النعيم, أهل الصفرا, ٥١٥, تراث عربي, قبائل الشام, حمص, الصفرا, عز الدين أبو حمرة, بلدة عز الدين, بلدة النعيم, أحمد بن نعيم'

// Default OG image
const DEFAULT_OG = 'https://qabilat-alnaim.qabilat-alnaim.workers.dev/images/logo.webp'

// Page-specific OG images (using existing WebP images)
const OG_IMAGES = {
  home: 'https://qabilat-alnaim.qabilat-alnaim.workers.dev/images/hero-banner-2026.webp',
  history: 'https://qabilat-alnaim.qabilat-alnaim.workers.dev/images/silsilat-al-nasb.webp',
  town: 'https://qabilat-alnaim.qabilat-alnaim.workers.dev/images/town-overview-v2.webp',
  camels: 'https://qabilat-alnaim.qabilat-alnaim.workers.dev/images/abnaa-izz-din-abu-himara.webp',
  horses: 'https://qabilat-alnaim.qabilat-alnaim.workers.dev/images/nasb-kull-ibn.webp',
  sheep: 'https://qabilat-alnaim.qabilat-alnaim.workers.dev/images/silsilat-al-nasb.webp',
  wasm: 'https://qabilat-alnaim.qabilat-alnaim.workers.dev/images/tribe-flag.webp',
  poetry: 'https://qabilat-alnaim.qabilat-alnaim.workers.dev/images/tribe-logo-calligraphy.webp',
  coffee: 'https://qabilat-alnaim.qabilat-alnaim.workers.dev/images/banner.webp',
  traditions: 'https://qabilat-alnaim.qabilat-alnaim.workers.dev/images/tribe-flag.webp',
  tent: 'https://qabilat-alnaim.qabilat-alnaim.workers.dev/images/mawlid-wa-nashaa.webp',
  badia: 'https://qabilat-alnaim.qabilat-alnaim.workers.dev/images/syrian-badia-2026.webp',
  blog: 'https://qabilat-alnaim.qabilat-alnaim.workers.dev/images/banner.webp',
  search: 'https://qabilat-alnaim.qabilat-alnaim.workers.dev/images/logo.webp',
} as const

export const seoConfig: Record<string, SEOProps> = {
  home: {
    title: 'قبيلة النعيم أهل الصفرا ٥١٥ | تراث عربي أصيل من حمص',
    description: 'قبيلة النعيم أهل الصفرا ٥١٥ - من أعرق القبائل العربية في بلاد الشام. نسب هاشمي متصل بالإمام الحسين رضي الله عنه. توثيق تراث الإبل والخيل والشعر النبطي، بلدة عز الدين أبو حمرة، حمص، الصفرا.',
    keywords: `${BASE_KEYWORDS}, نسب هاشمي, فروسية عربية, إبل صفراء, إبل أصيلة, أغنام النعيم, كرم الضيافة, تراث سوري, تاريخ عربي, قبائل سورية, شعر نبطي`,
    image: OG_IMAGES.home,
    url: '/',
    type: 'website',
  },
  history: {
    title: 'النسب والتاريخ | قبيلة السادة النعيم',
    description: 'سلسلة النسب الهاشمي لقبيلة السادة النعيم من الإمام الحسين رضي الله عنه. تاريخ القبيلة والبطون الأربعة الكبرى: الفخر، المحمدية، الحزومين، البو طارق.',
    keywords: `${BASE_KEYWORDS}, النسب الهاشمي, سلسلة النسب, البطون, الأفخاذ, الفخر, المحمدية, الحزومين, البو طارق, تاريخ القبائل العربية`,
    image: OG_IMAGES.history,
    url: '/history',
    type: 'article',
    section: 'التاريخ',
  },
  camels: {
    title: 'الإبل عند قبيلة السادة النعيم | تراث الصفرا',
    description: 'تربية الإبل عند قبيلة السادة النعيم - أهل الصفرا. سلالات الإبل الأصيلة، فنون الرعي في البادية، مكانة الإبل في التراث العربي الأصيل.',
    keywords: `${BASE_KEYWORDS}, إبل, إبل صفراء, إبل أصيلة, تربية الإبل, سلالات الإبل, البادية, رعي الإبل, تراث بدوي`,
    image: OG_IMAGES.camels,
    url: '/camels',
    type: 'article',
    section: 'التراث',
  },
  horses: {
    title: 'الخيل والفروسية | قبيلة السادة النعيم',
    description: 'الفروسية العربية الأصيلة عند قبيلة السادة النعيم. سلالات الخيل العربية الأصيلة، فنون الفروسية، الرماية على الخيل، وتاريخ الخيل في التراث العربي.',
    keywords: `${BASE_KEYWORDS}, فروسية, خيل عربي, خيل أصيلة, سلالات الخيل, فروسية عربية, الرماية على الخيل, الخيل العربية`,
    image: OG_IMAGES.horses,
    url: '/horses',
    type: 'article',
    section: 'التراث',
  },
  sheep: {
    title: 'الغنم عند قبيلة السادة النعيم | أصالة السلالة',
    description: 'تربية الغنم عند قبيلة السادة النعيم. سلالات الغنم الأصيلة، فنون العناية والرعي، مكانة الغنم في التراث العربي والحياة البدوية.',
    keywords: `${BASE_KEYWORDS}, غنم, أغنام, سلالات الغنم, تربية الأغنام, الرعي, البادية, تراث الغنم`,
    image: OG_IMAGES.sheep,
    url: '/sheep',
    type: 'article',
    section: 'التراث',
  },
  wasm: {
    title: 'الوسم ورمز ٥١٥ | قبيلة السادة النعيم',
    description: 'الوسم (رمز ٥١٥) عند قبيلة السادة النعيم. تاريخ الوسم، دلالته كرمز للانتماء والهوية، وكيفية وسم الإبل والأغنام في التراث العربي.',
    keywords: `${BASE_KEYWORDS}, وسم, رمز ٥١٥, وسم الإبل, وسم الأغنام, علامات القبائل, هوية الانتماء, تراث الوسم`,
    image: OG_IMAGES.wasm,
    url: '/wasm',
    type: 'article',
    section: 'التراث',
  },
  poetry: {
    title: 'الشعر النبطي | قصائد قبيلة السادة النعيم',
    description: 'الشعر النبطي والفخر عند قبيلة السادة النعيم. قصائد أهل الصفرا، المدائح والأرجاز، وأبيات الشعر التي تروي أمجاد القبيلة وتاريخها.',
    keywords: `${BASE_KEYWORDS}, شعر نبطي, قصائد فخر, شعر قبائل, أهل الصفرا, مدائح, أراجز, شعر عربي, شعر تراثي`,
    image: OG_IMAGES.poetry,
    url: '/poetry',
    type: 'article',
    section: 'الأدب',
  },
  coffee: {
    title: 'القهوة العربية | طقوس الضيافة عند قبيلة النعيم',
    description: 'القهوة العربية (الدلة) وطقوس الضيافة عند قبيلة السادة النعيم. فناجين الضيافة، كرم العرب، تقاليد إعداد القهوة واستقبال الضيف في التراث العربي.',
    keywords: `${BASE_KEYWORDS}, قهوة عربية, الدلة, فناجين, الضيافة العربية, كرم العرب, تقاليد الضيافة, قهوة بدوية`,
    image: OG_IMAGES.coffee,
    url: '/coffee',
    type: 'article',
    section: 'التراث',
  },
  traditions: {
    title: 'العادات والتقاليد | قبيلة السادة النعيم',
    description: 'العادات والتقاليد العربية الأصيلة عند قبيلة السادة النعيم. الكرم والضيافة، بيت الشعر، المجالس والأمجاد، وتقاليد القبيلة العربية العريقة.',
    keywords: `${BASE_KEYWORDS}, عادات, تقاليد, الكرم, الضيافة, المجالس, الأمجاد, أعراف عربية, قيم, أخلاق`,
    image: OG_IMAGES.traditions,
    url: '/traditions',
    type: 'article',
    section: 'التراث',
  },
  tent: {
    title: 'بيت الشعر | الخيمة البدوية عند قبيلة النعيم',
    description: 'بيت الشعر (الخيمة البدوية) عند قبيلة السادة النعيم. أقسام بيت الشعر، أجزاؤه، حباله وأدواته، دخلة البادية وكرم الضيافة في الخيمة.',
    keywords: `${BASE_KEYWORDS}, بيت شعر, خيمة, خيمة بدوية, الخيمة العربية, دخلة البادية, الشعر, كرم الضيافة, تقاليد الخيمة`,
    image: OG_IMAGES.tent,
    url: '/tent',
    type: 'article',
    section: 'التراث',
  },
  town: {
    title: 'بلدة عزّ الدين أبو حمرة | موطن قبيلة النعيم أهل الصفرا ٥١٥',
    description: 'بلدة عزّ الدين أبو حمرة - موطن قبيلة النعيم أهل الصفرا ٥١٥ التاريخي. قصة تسمية البلدة بالشيخ عزّ الدين أبو حمرة، معالمها من المساجد والبيوتات والمقامات، ودورها الاجتماعي والاقتصادي عبر التاريخ. من قلب بلاد الشام، إرث عربي أصيل يمتد عبر الأجيال.',
    keywords: `${BASE_KEYWORDS}, بلدة عز الدين, عز الدين أبو حمرة, موطن القبيلة, تاريخ البلدة, معالم البلدة, الجذور, الانتماء, بلدة النعيم, قرية النعيم, حمص, بلاد الشام, أحمد بن نعيم`,
    image: OG_IMAGES.town,
    url: '/town',
    type: 'article',
    section: 'التاريخ',
  },
  badia: {
    title: 'البادية السورية (الحماد) | مهد قبيلة النعيم أهل الصفرا ٥١٥',
    description: 'البادية السورية (الحماد) - هضبة بازلتية شاسعة في جنوب شرق سوريا، مهد قبيلة النعيم أهل الصفرا ٥١٥. الحماد السوري هضبة من الحجر البازلتي الأسود، موطن الإبل والخيل البدوية، تمتد على حمص ودير الزور والرقة وحماة. اكتشف أرض الأجداد وجغرافيا القبيلة وتاريخها العريق.',
    keywords: `${BASE_KEYWORDS}, البادية السورية, الحماد, الحماد السوري, هضبة البازلت, البادية, صحراء سوريا, مهد القبيلة, أرض الأجداد, حمص, دير الزور, الرقة, حماة, بلاد الشام, الإبل البدوية, المراعي الطبيعية, التراث البدوي`,
    image: OG_IMAGES.badia,
    url: '/badia',
    type: 'article',
    section: 'التراث',
  },
  blog: {
    title: 'المدونة | قبيلة السادة النعيم',
    description: 'أخبار ومقالات عن تاريخ وتراث قبيلة السادة النعيم. مقالات تثقيفية عن الإبل، الخيل، النسب، بلدة عز الدين، الشعر النبطي، والضيافة.',
    keywords: `مدونة, أخبار, مقالات, ${BASE_KEYWORDS}`,
    image: OG_IMAGES.blog,
    url: '/blog',
    type: 'website',
  },
  search: {
    title: 'بحث في الموقع | قبيلة السادة النعيم',
    description: 'ابحث في محتوى موقع قبيلة السادة النعيم - التراث، التاريخ، النسب، الإبل، الخيل، الشعر، والضيافة.',
    keywords: `بحث, ${BASE_KEYWORDS}`,
    image: OG_IMAGES.search,
    url: '/search',
    type: 'website',
  },
}
